export AWS_REGION="<YOUR-AWS-REGION>"
export KENDRA_INDEX_ID="<YOUR-KENDRA-INDEX-ID>"
export TEXT2TEXT_ENDPOINT_NAME="<YOUR-SAGEMANER-ENDPOINT-FOR-TEXT-GENERATION-MODEL>"
export PROVIDER_NAME="llama2"