apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-mcp-server
  labels:
    {{- include "observability-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana-mcp-server
spec:
  replicas: {{ .Values.grafanaMcpServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "observability-assistant.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana-mcp-server
  template:
    metadata:
      labels:
        {{- include "observability-assistant.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grafana-mcp-server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: grafana-mcp-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.grafanaMcpServer.image.repository }}:{{ .Values.grafanaMcpServer.image.tag }}"
          imagePullPolicy: {{ .Values.grafanaMcpServer.image.pullPolicy }}
          args:
            - "-t"
            - "streamable-http"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: GRAFANA_URL
              value: {{ .Values.grafanaMcpServer.env.grafanaUrl | quote }}
            - name: GRAFANA_API_KEY
              value: {{ .Values.grafanaMcpServer.env.grafanaApiKey | quote }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.grafanaMcpServer.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 