apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability-assistant.fullname" . }}
  labels:
    {{- include "observability-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: observability-assistant
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: {{ .Values.observabilityAssistant.service.type }}
  ports:
    - port: {{ .Values.observabilityAssistant.service.port }}
      targetPort: {{ .Values.observabilityAssistant.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "observability-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: observability-assistant 