apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-mcp-server
  labels:
    {{- include "observability-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: tempo-mcp-server
spec:
  replicas: {{ .Values.tempoMcpServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "observability-assistant.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: tempo-mcp-server
  template:
    metadata:
      labels:
        {{- include "observability-assistant.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: tempo-mcp-server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: tempo-mcp-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.tempoMcpServer.image.repository }}:{{ .Values.tempoMcpServer.image.tag }}"
          imagePullPolicy: {{ .Values.tempoMcpServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: TEMPO_URL
              value: {{ .Values.tempoMcpServer.env.tempoUrl | quote }}
            - name: TEMPO_USERNAME
              value: {{ .Values.tempoMcpServer.env.tempoUsername | quote }}
            - name: TEMPO_PASSWORD
              value: {{ .Values.tempoMcpServer.env.tempoPassword | quote }}
            - name: TEMPO_TOKEN
              value: {{ .Values.tempoMcpServer.env.tempoToken | quote }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.tempoMcpServer.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 